services:
  - type: web
    name: freevibes-node-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: https://tu-frontend-vercel.vercel.app
      - key: YOUTUBE_API_URL
        sync: false # Se configurará manualmente
